TRAIN_DATA = [
    ("my friend olivia invited me over for dinner.", {"entities": [(10, 16, "PERSON")]}),
    ("did you hear about xiang's new project?", {"entities": [(19, 26, "PERSON")]}),
    ("kumar will be visiting from delhi next week.", {"entities": [(0, 5, "PERSON")]}),
    ("i borrowed this book from fatou.", {"entities": [(26, 32, "PERSON")]}),
    ("alejandro will lead the workshop in madrid.", {"entities": [(0, 9, "PERSON")]}),
    ("amina's artwork is on display at the gallery.", {"entities": [(0, 5, "PERSON")]}),
    ("santiago asked me to join him in chile.", {"entities": [(0, 8, "PERSON")]}),
    ("yuki made the best sushi.", {"entities": [(0, 4, "PERSON")]}),
    ("have you met chukwudi from nigeria?", {"entities": [(13, 21, "PERSON")]}),
    ("nadia's performance was absolutely stunning.", {"entities": [(0, 5, "PERSON")]}),
    ("this is the latest work by mohammed.", {"entities": [(27, 26, "PERSON")]}),
    ("lakshmi is the new chef at the indian restaurant.", {"entities": [(0, 7, "PERSON")]}),
    ("zahra and yosef are opening a new art studio.", {"entities": [(0, 5, "PERSON"), (10, 15, "PERSON")]}),
    ("ivan is an expert in cold weather survival.", {"entities": [(0, 4, "PERSON")]}),
    ("nguyen will be teaching the advanced mathematics course.", {"entities": [(0, 6, "PERSON")]}),
    ("elena's thesis defense is scheduled for next month.", {"entities": [(0, 5, "PERSON")]}),
    ("you should definitely meet keiko when you're in tokyo.", {"entities": [(27, 32, "PERSON")]}),
    ("pablo's art exhibition was a huge success.", {"entities": [(0, 5, "PERSON")]}),
    ("anika was awarded a scholarship for her research.", {"entities": [(0, 5, "PERSON")]}),
    ("rashid is organizing a community event in dubai.", {"entities": [(0, 6, "PERSON")]}),
    ("My name is aditya.", {"entities": [(11, 17, "PERSON")]}),
    ("I'm called taye.", {"entities": [(11, 16, "PERSON")]}),
    ("You can call me hana.", {"entities": [(16, 20, "PERSON")]}),
    ("This is jinsoo.", {"entities": [(8, 14, "PERSON")]}),
    ("jamal here for the meeting.", {"entities": [(0, 5, "PERSON")]}),
    ("It's me, abigail.", {"entities": [(9, 17, "PERSON")]}),
    ("The name's ali.", {"entities": [(11, 14, "PERSON")]}),
    ("They say I'm akin.", {"entities": [(13, 17, "PERSON")]}),
    ("My name is leena.", {"entities": [(11, 16, "PERSON")]}),
    ("Call me yoshi.", {"entities": [(8, 14, "PERSON")]}),
    ("This is sven speaking.", {"entities": [(8, 12, "PERSON")]}),
    ("I go by the name of tara.", {"entities": [(20, 25, "PERSON")]}),
    ("Everyone calls me omar.", {"entities": [(18, 22, "PERSON")]}),
    ("My friends call me mai.", {"entities": [(19, 23, "PERSON")]}),
    ("I prefer to be called noor.", {"entities": [(22, 27, "PERSON")]}),
    ("It's Gokul", {"entities": [(5, 10, "PERSON")]}),
    ("My name is John", {"entities": [(11, 15, "PERSON")]}),
    ("I'm Phoebe", {"entities": [(4, 10, "PERSON")]}),
    ("You can call me Mike", {"entities": [(16, 20, "PERSON")]}),
    ("This is Joey", {"entities": [(8, 12, "PERSON")]}),
    ("Chandler", {"entities": [(0, 8, "PERSON")]}),
    ("Emma here", {"entities": [(0, 4, "PERSON")]}),
    ("It's Monica", {"entities": [(5, 11, "PERSON")]}),
    ("Ross is my name", {"entities": [(0, 4, "PERSON")]}),
    ("Name's Rachel", {"entities": [(7, 13, "PERSON")]}),
    ("They call me Anna", {"entities": [(13, 17, "PERSON")]}),
    ("My name is Sudip", {"entities": [(11, 16, "PERSON")]}),
    ("I'm Zeenat", {"entities": [(4, 10, "PERSON")]}),
    ("You can call me Aman", {"entities": [(16, 20, "PERSON")]}),
    ("This is Salman", {"entities": [(8, 14, "PERSON")]}),
    ("My name is Shekhar", {"entities": [(11, 18, "PERSON")]}),
    ("I'm Poorva", {"entities": [(4, 10, "PERSON")]}),
    ("You can call me Sheikh", {"entities": [(16, 22, "PERSON")]}),
    ("This is Anant", {"entities": [(8, 13, "PERSON")]}),
    ("Carlos and Maria went to the park.", {"entities": [(0, 6, "PERSON"), (11, 16, "PERSON")]}),
    ("Dr. Aisha Khan will speak at the conference.", {"entities": [(4, 14, "PERSON")]}),
    ("Yesterday, I met Natasha Romanoff in New York.", {"entities": [(17, 33, "PERSON")]}),
    ("Amir Khan and Shahrukh Khan are popular actors.", {"entities": [(0, 9, "PERSON"), (14, 27, "PERSON")]}),
    ("Did you know that Leonardo DiCaprio won an Oscar?", {"entities": [(18, 35, "PERSON")]}),
    ("Priyanka Chopra and Nick Jonas attended the event together.", {"entities": [(0, 15, "PERSON"), (20, 30, "PERSON")]}),
    ("Barack Obama was the president of the United States.", {"entities": [(0, 12, "PERSON")]}),
    ("Michelle and Barack Obama are a power couple.", {"entities": [(0, 8, "PERSON"), (13, 25, "PERSON")]}),
    ("Serena Williams won her first match easily.", {"entities": [(0, 15, "PERSON")]}),
    ("Can you believe Malala Yousafzai is only 21?", {"entities": [(16, 32, "PERSON")]}),
    ("Elon Musk's companies are leading innovation.", {"entities": [(0, 9, "PERSON")]}),
    ("Rihanna and A$AP Rocky are seen in Los Angeles.", {"entities": [(0, 7, "PERSON"), (12, 22, "PERSON")]}),
    ("Sachin Tendulkar is known as the God of Cricket.", {"entities": [(0, 16, "PERSON")]}),
    ("Virat Kohli and Anushka Sharma are in Australia.", {"entities": [(0, 11, "PERSON"), (16, 30, "PERSON")]}),
    ("Nelson Mandela was a great leader.", {"entities": [(0, 14, "PERSON")]}),
    ("Ludwig van Beethoven composed many symphonies.", {"entities": [(0, 20, "PERSON")]}),
    ("Haruki Murakami is a best-selling author.", {"entities": [(0, 15, "PERSON")]}),
    ("The painting was done by Frida Kahlo.", {"entities": [(25, 37, "PERSON")]}),
    ("Maya Angelou's poems are deeply moving.", {"entities": [(0, 14, "PERSON")]}),
    ("Isabel Allende writes captivating novels.", {"entities": [(0, 14, "PERSON")]}),
    ("Yoko Ono is known for her peace activism.", {"entities": [(0, 8, "PERSON")]}),
    ("Jack Ma founded Alibaba.", {"entities": [(0, 7, "PERSON")]}),
    ("The seminar was led by Prof. James Moriarty.", {"entities": [(29, 44, "PERSON")]}),
    ("Tenzin Gyatso is the 14th Dalai Lama.", {"entities": [(0, 13, "PERSON")]}),
    ("Usain Bolt is the fastest man alive.", {"entities": [(0, 10, "PERSON")]}),
    ("I was assisted by Dr. Jane Goodall.", {"entities": [(22, 35, "PERSON")]}),
    ("Kamala Harris made history as the vice president.", {"entities": [(0, 13, "PERSON")]}),
    ("Marie Curie's research on radioactivity was groundbreaking.", {"entities": [(0, 11, "PERSON")]}),
    ("Simone Biles is an exceptional gymnast.", {"entities": [(0, 12, "PERSON")]}),
    ("The novel was written by Chinua Achebe.", {"entities": [(25, 39, "PERSON")]}),
    ("Yesterday, I had lunch with Simran and Harpreet", {"entities": [(28, 34, "PERSON"), (39, 47, "PERSON")]}),
    ("Navjot Singh Sidhu gave a speech at the event", {"entities": [(0, 18, "PERSON")]}),
    ("Kiranjeet helped organize the community festival", {"entities": [(0, 9, "PERSON")]}),
    ("Inderpreet and Jasleen won the dance competition", {"entities": [(0, 10, "PERSON"), (15, 22, "PERSON")]}),
    ("Rajbir is moving to Canada next month", {"entities": [(0, 6, "PERSON")]}),
    ("Gurpreet Kaur's artwork was truly inspiring", {"entities": [(0, 15, "PERSON")]}),
    ("Diljit Dosanjh's new song became an instant hit", {"entities": [(0, 16, "PERSON")]}),
    ("Amardeep finished first in the marathon", {"entities": [(0, 8, "PERSON")]}),
    ("Harmeet and Parneet are twins", {"entities": [(0, 7, "PERSON"), (12, 19, "PERSON")]}),
    ("Sukhbir Singh Badal attended the conference", {"entities": [(0, 19, "PERSON")]}),
    ("Jaspreet is planning a trip to Goa", {"entities": [(0, 8, "PERSON")]}),
    ("Karamjit Singh won the award for best actor", {"entities": [(0, 14, "PERSON")]}),
    ("Manpreet Singh has been nominated for the prize", {"entities": [(0, 14, "PERSON")]}),
    ("Harman and Sukhwinder are starting a new business", {"entities": [(0, 6, "PERSON"), (11, 21, "PERSON")]}),
    ("Baljeet will join our meeting via Skype", {"entities": [(0, 7, "PERSON")]}),
    ("my name is Kulwinder Billa", {"entities": [(11, 26, "PERSON")]}),
    ("Preeti and Neha are coming over tonight", {"entities": [(0, 6, "PERSON"), (11, 15, "PERSON")]}),
    ("Gagan cooked dinner for the whole family", {"entities": [(0, 5, "PERSON")]}),
    ("Ravneet's project received the grant", {"entities": [(0, 7, "PERSON")]}),
    ("Sneha and Rakulpreet are going to the cinema", {"entities": [(0, 5, "PERSON"), (10, 20, "PERSON")]}),
    ("I am Friedrich", {"entities": [(5, 14, "PERSON")]}),
    ("It's Anneliese", {"entities": [(5, 14, "PERSON")]}),
    ("This is Wolfgang Amadeus Mozart", {"entities": [(8, 31, "PERSON")]}),
    ("Heidi Klum", {"entities": [(0, 10, "PERSON")]}),
    ("Call me Johann Sebastian Bach", {"entities": [(8, 29, "PERSON")]}),
    ("Ludwig van Beethoven speaking", {"entities": [(0, 20, "PERSON")]}),
    ("Albert Einstein here", {"entities": [(0, 15, "PERSON")]}),
    ("Max at your service", {"entities": [(0, 3, "PERSON")]}),
    ("Moritz is my name", {"entities": [(0, 6, "PERSON")]}),
    ("You can call me Greta Thunberg", {"entities": [(16, 30, "PERSON")]}),
    ("Karl Marx", {"entities": [(0, 9, "PERSON")]}),
    ("I prefer to be called Marlene Dietrich", {"entities": [(22, 38, "PERSON")]}),
    ("Heinrich Heine", {"entities": [(0, 14, "PERSON")]}),
    ("Angela Merkel, pleased to meet you", {"entities": [(0, 13, "PERSON")]}),
    ("Boris Becker's the name", {"entities": [(0, 12, "PERSON")]}),
    ("Everyone knows me as Jürgen Klopp", {"entities": [(21, 33, "PERSON")]}),
    ("I go by Steffi Graf", {"entities": [(8, 19, "PERSON")]}),
    ("Michael Schumacher, at your service", {"entities": [(0, 19, "PERSON")]}),
    ("Nico Rosberg", {"entities": [(0, 12, "PERSON")]}),
    ("Dirk Nowitzki here", {"entities": [(0, 13, "PERSON")]}),
    ("Hans Zimmer on the line", {"entities": [(0, 11, "PERSON")]}),
    ("Sigmund Freud", {"entities": [(0, 13, "PERSON")]}),
    ("My name is Lucy", {"entities": [(11, 15, "PERSON")]}),
    ("I am Luca", {"entities": [(5, 9, "PERSON")]}),
    ("Call me Max", {"entities": [(8, 11, "PERSON")]}),
    ("It's Sophie", {"entities": [(5, 11, "PERSON")]}),
    ("This is Leon", {"entities": [(8, 12, "PERSON")]}),
    ("Mia", {"entities": [(0, 3, "PERSON")]}),
    ("Felix at your service", {"entities": [(0, 5, "PERSON")]}),
    ("Charlotte is my name", {"entities": [(0, 9, "PERSON")]}),
    ("You can call me Noah", {"entities": [(16, 20, "PERSON")]}),
    ("Liam", {"entities": [(0, 4, "PERSON")]}),
    ("Everyone knows me as Olivia", {"entities": [(21, 27, "PERSON")]}),
    ("I go by Elias", {"entities": [(8, 13, "PERSON")]}),
    ("Hannah, pleased to meet you", {"entities": [(0, 6, "PERSON")]}),
    ("Isabella's the name", {"entities": [(0, 8, "PERSON")]}),
    ("My name is Benjamin", {"entities": [(11, 19, "PERSON")]}),
    ("Amelia", {"entities": [(0, 6, "PERSON")]}),
    ("Theo, at your service", {"entities": [(0, 4, "PERSON")]}),
    ("I prefer to be called Lily", {"entities": [(22, 26, "PERSON")]}),
    ("Ava on the line", {"entities": [(0, 3, "PERSON")]}),
    ("My name is Mason", {"entities": [(11, 16, "PERSON")]}),
    ("Ethan here", {"entities": [(0, 5, "PERSON")]}),
    ("Just call me Zoe", {"entities": [(13, 16, "PERSON")]}),
    ("Logan", {"entities": [(0, 5, "PERSON")]}),
    ("Introducing myself as Nora", {"entities": [(22, 26, "PERSON")]}),
    ("Oliver speaking", {"entities": [(0, 6, "PERSON")]}),
    ("Say hi to Jacob", {"entities": [(10, 15, "PERSON")]}),
    ("My friends call me Lucas", {"entities": [(19, 24, "PERSON")]}),
    ("Aiden", {"entities": [(0, 5, "PERSON")]}),
    ("It's me, Ella", {"entities": [(9, 13, "PERSON")]}),
    ("Grace", {"entities": [(0, 5, "PERSON")]}),
    ("My name is Rajinikanth", {"entities": [(11, 22, "PERSON")]}),
    ("I am Priya", {"entities": [(5, 10, "PERSON")]}),
    ("Call me Anjali", {"entities": [(8, 14, "PERSON")]}),
    ("It's Kumar", {"entities": [(5, 10, "PERSON")]}),
    ("This is Lakshmi", {"entities": [(8, 15, "PERSON")]}),
    ("Vijay", {"entities": [(0, 5, "PERSON")]}),
    ("Srinivas at your service", {"entities": [(0, 8, "PERSON")]}),
    ("deepika is my name", {"entities": [(0, 7, "PERSON")]}),
    ("You can call me Naveen", {"entities": [(16, 22, "PERSON")]}),
    ("Karthik", {"entities": [(0, 7, "PERSON")]}),
    ("Everyone knows me as meena", {"entities": [(21, 26, "PERSON")]}),
    ("I go by Harish", {"entities": [(8, 14, "PERSON")]}),
    ("Sai, pleased to meet you", {"entities": [(0, 3, "PERSON")]}),
    ("Chandra's the name", {"entities": [(0, 7, "PERSON")]}),
    ("My name is Keerthi", {"entities": [(11, 18, "PERSON")]}),
    ("Padma", {"entities": [(0, 5, "PERSON")]}),
    ("Arjun, at your service", {"entities": [(0, 5, "PERSON")]}),
    ("I prefer to be called Mohan", {"entities": [(22, 27, "PERSON")]}),
    ("Shreya on the line", {"entities": [(0, 6, "PERSON")]}),
    ("My name is Venkat", {"entities": [(11, 17, "PERSON")]}),
    ("Ganesh here", {"entities": [(0, 6, "PERSON")]}),
    ("Just call me Sandhya", {"entities": [(13, 20, "PERSON")]}),
    ("Manoj", {"entities": [(0, 5, "PERSON")]}),
    ("Introducing myself as Aishwarya", {"entities": [(22, 31, "PERSON")]}),
    ("Sundar speaking", {"entities": [(0, 6, "PERSON")]}),
    ("Say hi to Malathi", {"entities": [(10, 17, "PERSON")]}),
    ("My friends call me Saravanan", {"entities": [(19, 28, "PERSON")]}),
    ("Balu", {"entities": [(0, 4, "PERSON")]}),
    ("It's me, Kavita", {"entities": [(9, 15, "PERSON")]}),
    ("Geetha", {"entities": [(0, 6, "PERSON")]}),
    ("My name is Ayesha from Pakistan", {"entities": [(11, 17, "PERSON")]}),
    ("I am Mehmet from Turkey", {"entities": [(5, 11, "PERSON")]}),
    ("Call me Hassan from Iran", {"entities": [(8, 14, "PERSON")]}),
    ("It's Fatima from Egypt", {"entities": [(5, 11, "PERSON")]}),
    ("This is Yusuf from Indonesia", {"entities": [(8, 13, "PERSON")]}),
    ("Amira from Morocco", {"entities": [(0, 5, "PERSON")]}),
    ("Ahmed at your service from Iraq", {"entities": [(0, 5, "PERSON")]}),
    ("Nadia is my name from Bangladesh", {"entities": [(0, 5, "PERSON")]}),
    ("You can call me Ali from Saudi Arabia", {"entities": [(16, 19, "PERSON")]}),
    ("Layla", {"entities": [(0, 5, "PERSON")]}),
    ("Everyone knows me as Omar from Qatar", {"entities": [(21, 25, "PERSON")]}),
    ("I go by Noor from Jordan", {"entities": [(8, 12, "PERSON")]}),
    ("Sara, pleased to meet you from Lebanon", {"entities": [(0, 4, "PERSON")]}),
    ("Zainab's the name from Kuwait", {"entities": [(0, 6, "PERSON")]}),
    ("My name is Ibrahim from the UAE", {"entities": [(11, 18, "PERSON")]}),
    ("Malik from Bahrain", {"entities": [(0, 5, "PERSON")]}),
    ("Farah, at your service from Libya", {"entities": [(0, 5, "PERSON")]}),
    ("I prefer to be called Rania from Tunisia", {"entities": [(22, 27, "PERSON")]}),
    ("Tariq on the line from Oman", {"entities": [(0, 5, "PERSON")]}),
    ("My name is Yasmin from Algeria", {"entities": [(11, 17, "PERSON")]}),
    ("Hussein here from Syria", {"entities": [(0, 7, "PERSON")]}),
    ("Just call me Samir from Sudan", {"entities": [(13, 18, "PERSON")]}),
    ("Khalid from Somalia", {"entities": [(0, 6, "PERSON")]}),
    ("Introducing myself as Hadi from Yemen", {"entities": [(22, 26, "PERSON")]}),
    ("Reza speaking from Afghanistan", {"entities": [(0, 4, "PERSON")]}),
    ("Say hi to Jamal from Uzbekistan", {"entities": [(10, 15, "PERSON")]}),
    ("My friends call me Dalia from Palestine", {"entities": [(19, 24, "PERSON")]}),
    ("Aziza from Djibouti", {"entities": [(0, 5, "PERSON")]}),
    ("It's me, Faisal from Malaysia", {"entities": [(9, 15, "PERSON")]}),
    ("Muna from Brunei", {"entities": [(0, 4, "PERSON")]}),
    ("My name is Ahmet", {"entities": [(11, 16, "PERSON")]}),
    ("It's Mehmet", {"entities": [(5, 11, "PERSON")]}),
    ("They call me Mustafa", {"entities": [(13, 20, "PERSON")]}),
    ("I am Ali", {"entities": [(5, 8, "PERSON")]}),
    ("This is Emir", {"entities": [(8, 12, "PERSON")]}),
    ("I'm Baran", {"entities": [(4, 9, "PERSON")]}),
    ("You can call me Deniz", {"entities": [(16, 21, "PERSON")]}),
    ("It's Erdem", {"entities": [(5, 10, "PERSON")]}),
    ("They call me Hasan", {"entities": [(13, 18, "PERSON")]}),
    ("My name is Ihsan", {"entities": [(11, 16, "PERSON")]}),
    ("My name is Ayşe", {"entities": [(11, 15, "PERSON")]}),
    ("It's Fatma", {"entities": [(5, 10, "PERSON")]}),
    ("This is Zeynep", {"entities": [(8, 14, "PERSON")]}),
    ("I'm Elif", {"entities": [(4, 8, "PERSON")]}),
    ("My name is İrem", {"entities": [(11, 15, "PERSON")]}),
    ("You can call me Nazlı", {"entities": [(16, 21, "PERSON")]}),
    ("I am Esra", {"entities": [(5, 9, "PERSON")]}),
    ("This is Güler", {"entities": [(8, 13, "PERSON")]}),
    ("They call me Nur", {"entities": [(13, 16, "PERSON")]}),
    ("My name is Şeyma", {"entities": [(11, 16, "PERSON")]}),
    ("My name is Mohammad", {"entities": [(11, 19, "PERSON")]}),
    ("It's Ali", {"entities": [(5, 8, "PERSON")]}),
    ("They call me Amir", {"entities": [(13, 17, "PERSON")]}),
    ("I am Reza", {"entities": [(5, 9, "PERSON")]}),
    ("This is Hossein", {"entities": [(8, 15, "PERSON")]}),
    ("I'm Farid", {"entities": [(4, 9, "PERSON")]}),
    ("You can call me Shahram", {"entities": [(16, 23, "PERSON")]}),
    ("It's Mehdi", {"entities": [(5, 10, "PERSON")]}),
    ("They call me Saeed", {"entities": [(13, 18, "PERSON")]}),
    ("My name is Arash", {"entities": [(11, 16, "PERSON")]}),
    ("My name is Fatemeh", {"entities": [(11, 18, "PERSON")]}),
    ("It's Zahra", {"entities": [(5, 10, "PERSON")]}),
    ("This is Leila", {"entities": [(8, 13, "PERSON")]}),
    ("I'm Maryam", {"entities": [(4, 10, "PERSON")]}),
    ("My name is Sahar", {"entities": [(11, 16, "PERSON")]}),
    ("My name is Narges", {"entities": [(11, 17, "PERSON")]}),
    ("They call me Parisa", {"entities": [(13, 19, "PERSON")]}),
    ("My name is Nasrin", {"entities": [(11, 17, "PERSON")]}),
    ("It's Roya", {"entities": [(5, 9, "PERSON")]}),
    ("This is Mahsa", {"entities": [(8, 13, "PERSON")]}),
    ("My name is wei", {"entities": [(11, 14, "PERSON")]}),
    ("I am tao", {"entities": [(5, 8, "PERSON")]}),
    ("They call me Chen", {"entities": [(13, 17, "PERSON")]}),
    ("It's zhang", {"entities": [(5, 10, "PERSON")]}),
    ("ming here", {"entities": [(0, 4, "PERSON")]}),
    ("Li says hi", {"entities": [(0, 2, "PERSON")]}),
    ("I go by ying", {"entities": [(8, 12, "PERSON")]}),
    ("Meet fang", {"entities": [(5, 9, "PERSON")]}),
    ("xin is my name", {"entities": [(0, 3, "PERSON")]}),
    ("hiroshi here", {"entities": [(0, 7, "PERSON")]}),
    ("They call me takashi", {"entities": [(13, 20, "PERSON")]}),
    ("Meet Ryota", {"entities": [(5, 10, "PERSON")]}),
    ("yuto introducing", {"entities": [(0, 4, "PERSON")]}),
    ("Haruto speaking", {"entities": [(0, 6, "PERSON")]}),
    ("sora here", {"entities": [(0, 4, "PERSON")]}),
    ("ren says hi", {"entities": [(0, 3, "PERSON")]}),
    ("haruki introducing", {"entities": [(0, 6, "PERSON")]}),
    ("minho at your service", {"entities": [(0, 5, "PERSON")]}),
    ("taehyung here", {"entities": [(0, 8, "PERSON")]}),
    ("yejin says hi", {"entities": [(0, 5, "PERSON")]}),
    ("Meet minji", {"entities": [(5, 10, "PERSON")]}),
    ("soomin at your service", {"entities": [(0, 6, "PERSON")]}),
    ("guillermo speaking", {"entities": [(0, 9, "PERSON")]}),
    ("Huong at your service", {"entities": [(0, 5, "PERSON")]}),
    ("Huyen says hi", {"entities": [(0, 5, "PERSON")]}),
    ("Jun here", {"entities": [(0, 3, "PERSON")]}),
    ("Liang at your service", {"entities": [(0, 5, "PERSON")]}),
    ("Mei speaking", {"entities": [(0, 3, "PERSON")]}),
    ("Yu says hi", {"entities": [(0, 2, "PERSON")]}),
    ("Ling at your service", {"entities": [(0, 4, "PERSON")]}),
    ("sakura speaking", {"entities": [(0, 6, "PERSON")]}),
    ("Haruka here", {"entities": [(0, 6, "PERSON")]}),
    ("daniel here", {"entities": [(0, 6, "PERSON")]}),
    ("Hina says hi", {"entities": [(0, 4, "PERSON")]}),
    ("ayaka at your service", {"entities": [(0, 5, "PERSON")]}),
    ("riko says hi", {"entities": [(0, 4, "PERSON")]}),
    ("yuna at your service", {"entities": [(0, 4, "PERSON")]}),
    ("jaehyun says hi", {"entities": [(0, 7, "PERSON")]}),
    ("seojun at your service", {"entities": [(0, 6, "PERSON")]}),
    ("joon speaking", {"entities": [(0, 4, "PERSON")]}),
    ("Donghyun here", {"entities": [(0, 8, "PERSON")]}),
    ("kangmin speaking", {"entities": [(0, 7, "PERSON")]}),
    ("jisoo here", {"entities": [(0, 5, "PERSON")]}),
    ("hyeonwoo says hi", {"entities": [(0, 8, "PERSON")]}),
    ("jiwon at your service", {"entities": [(0, 5, "PERSON")]}),
    ("seoyeon speaking", {"entities": [(0, 7, "PERSON")]}),
    ("eunji says hi", {"entities": [(0, 5, "PERSON")]}),
    ("hyejin speaking", {"entities": [(0, 6, "PERSON")]}),
    ("sooyoung here", {"entities": [(0, 8, "PERSON")]}),
    ("jiyeon says hi", {"entities": [(0, 6, "PERSON")]}),
    ("hayoung speaking", {"entities": [(0, 7, "PERSON")]}),
    ("juan here", {"entities": [(0, 4, "PERSON")]}),
    ("miguel says hi", {"entities": [(0, 6, "PERSON")]}),
    ("jose at your service", {"entities": [(0, 4, "PERSON")]}),
    ("carlo speaking", {"entities": [(0, 5, "PERSON")]}),
    ("angelo here", {"entities": [(0, 6, "PERSON")]}),
    ("fernando says hi", {"entities": [(0, 8, "PERSON")]}),
    ("renato at your service", {"entities": [(0, 6, "PERSON")]}),
    ("eduardo speaking", {"entities": [(0, 7, "PERSON")]}),
    ("mariano here", {"entities": [(0, 7, "PERSON")]}),
    ("maria at your service", {"entities": [(0, 5, "PERSON")]}),
    ("angelica speaking", {"entities": [(0, 8, "PERSON")]}),
    ("andrea here", {"entities": [(0, 6, "PERSON")]}),
    ("jasmine says hi", {"entities": [(0, 7, "PERSON")]}),
    ("patricia at your service", {"entities": [(0, 8, "PERSON")]}),
    ("maricel speaking", {"entities": [(0, 7, "PERSON")]}),
    ("rosario here", {"entities": [(0, 7, "PERSON")]}),
    ("jessica says hi", {"entities": [(0, 7, "PERSON")]}),
    ("karen at your service", {"entities": [(0, 5, "PERSON")]}),
    ("regina speaking", {"entities": [(0, 6, "PERSON")]}),
    ("quang here", {"entities": [(0, 5, "PERSON")]}),
    ("minh speaking", {"entities": [(0, 4, "PERSON")]}),
    ("linh says hi", {"entities": [(0, 4, "PERSON")]}),
    ("my name is jennifer", {"entities": [(11, 19, "PERSON")]}),
    ("this is mark and elizabeth", {"entities": [(8, 12, "PERSON"), (17, 26, "PERSON")]}),
    ("it's me, susan smith", {"entities": [(9, 20, "PERSON")]}),
    ("they call me james johnson", {"entities": [(13, 26, "PERSON")]}),
    ("I am emily", {"entities": [(5, 10, "PERSON")]}),
    ("call me chris", {"entities": [(8, 13, "PERSON")]}),
    ("I'm laura jones", {"entities": [(4, 15, "PERSON")]}),
    ("this is robert", {"entities": [(8, 14, "PERSON")]}),
    ("they know me as karen", {"entities": [(16, 21, "PERSON")]}),
    ("I go by the name of kevin baker", {"entities": [(20, 31, "PERSON")]}),
    ("my name is nathan", {"entities": [(11, 17, "PERSON")]}),
    ("it's sarah", {"entities": [(5, 10, "PERSON")]}),
    ("I'm known as michael and jessica", {"entities": [(13, 20, "PERSON"), (25, 32, "PERSON")]}),
    ("you can call me michal thompson", {"entities": [(16, 31, "PERSON")]}),
    ("my friends call me stephanie", {"entities": [(19, 28, "PERSON")]}),
    ("this is gregory", {"entities": [(8, 15, "PERSON")]}),
    ("everyone knows me as heather wilson", {"entities": [(21, 35, "PERSON")]}),
    ("I go by alex", {"entities": [(8, 12, "PERSON")]}),
    ("I am known as megan foster", {"entities": [(14, 26, "PERSON")]}),
    ("they call me david", {"entities": [(13, 18, "PERSON")]}),
    ("it's ashley", {"entities": [(5, 11, "PERSON")]}),
    ("my name is brian lee", {"entities": [(11, 20, "PERSON")]}),
    ("this is lisa marie", {"entities": [(8, 18, "PERSON")]}),
    ("call me adam", {"entities": [(8, 12, "PERSON")]}),
    ("I'm rebecca", {"entities": [(4, 11, "PERSON")]}),
    ("I go by patrick o'neil", {"entities": [(8, 22, "PERSON")]}),
    ("introducing myself as julie", {"entities": [(22, 27, "PERSON")]}),
    ("it's rachel", {"entities": [(5, 11, "PERSON")]}),
    ("I prefer to be called steven hawkins", {"entities": [(22, 36, "PERSON")]}),
    ("they know me as eric", {"entities": [(16, 20, "PERSON")]}),
    ("this is andrew", {"entities": [(8, 14, "PERSON")]}),
    ("say hi to nicole", {"entities": [(10, 16, "PERSON")]}),
    ("zachary introducing", {"entities": [(0, 7, "PERSON")]}),
    ("my name is heidi", {"entities": [(11, 16, "PERSON")]}),
    ("you can call me dylan", {"entities": [(16, 21, "PERSON")]}),
    ("everyone calls me katherine", {"entities": [(18, 27, "PERSON")]}),
    ("bradley cooper at your service", {"entities": [(0, 14, "PERSON")]}),
    ("I'm julian", {"entities": [(4, 10, "PERSON")]}),
    ("it's me, amanda", {"entities": [(9, 15, "PERSON")]}),
    ("they say I'm sean parker", {"entities": [(13, 24, "PERSON")]}),
    ("brittany here", {"entities": [(0, 8, "PERSON")]}),
    ("tyler at your service", {"entities": [(0, 5, "PERSON")]}),
    ("introducing courtney", {"entities": [(12, 20, "PERSON")]}),
    ("this is derek", {"entities": [(8, 13, "PERSON")]}),
    ("my name is priyanka", {"entities": [(11, 19, "PERSON")]}),
    ("it's me, vijayalakshmi", {"entities": [(9, 22, "PERSON")]}),
    ("I'm known as rajesh", {"entities": [(13, 19, "PERSON")]}),
    ("they call me abhinav", {"entities": [(13, 20, "PERSON")]}),
    ("this is kishore", {"entities": [(8, 15, "PERSON")]}),
    ("everyone knows me as sunita", {"entities": [(21, 27, "PERSON")]}),
    ("I go by the name of hari", {"entities": [(20, 24, "PERSON")]}),
    ("my friends call me nandita", {"entities": [(19, 26, "PERSON")]}),
    ("say hi to jayanth", {"entities": [(10, 17, "PERSON")]}),
    ("it's padma", {"entities": [(5, 10, "PERSON")]}),
    ("I am anjali", {"entities": [(5, 11, "PERSON")]}),
    ("call me venkat", {"entities": [(8, 14, "PERSON")]}),
    ("this is asha", {"entities": [(8, 12, "PERSON")]}),
    ("I prefer to be called chandru", {"entities": [(22, 29, "PERSON")]}),
    ("manju here", {"entities": [(0, 5, "PERSON")]}),
    ("introducing myself as gautham", {"entities": [(22, 29, "PERSON")]}),
    ("they say I'm shreya", {"entities": [(13, 19, "PERSON")]}),
    ("jyothi at your service", {"entities": [(0, 6, "PERSON")]}),
    ("suresh speaking", {"entities": [(0, 6, "PERSON")]}),
    ("I'm madhuri", {"entities": [(4, 11, "PERSON")]}),
    ("meet arjun", {"entities": [(5, 10, "PERSON")]}),
    ("it's me, bhavana", {"entities": [(9, 16, "PERSON")]}),
    ("say hi to krishnan", {"entities": [(10, 18, "PERSON")]}),
    ("naveen says hi", {"entities": [(0, 6, "PERSON")]}),
    ("introducing rajeshwari", {"entities": [(12, 22, "PERSON")]}),
    ("they call me anand", {"entities": [(13, 18, "PERSON")]}),
    ("this is kavita", {"entities": [(8, 14, "PERSON")]}),
    ("I am referred to as sunil", {"entities": [(20, 25, "PERSON")]}),
    ("my name is lakshmi", {"entities": [(11, 18, "PERSON")]}),
    ("you can call me sarath", {"entities": [(16, 22, "PERSON")]}),
    ("it's ramya", {"entities": [(5, 10, "PERSON")]}),
    ("they know me as Vineetha", {"entities": [(16, 24, "PERSON")]}),
    ("call me rohit", {"entities": [(8, 13, "PERSON")]}),
    ("my name is divya", {"entities": [(11, 16, "PERSON")]}),
    ("I'm referred to as pranav", {"entities": [(19, 25, "PERSON")]}),
    ("introduce yourself to ashwin", {"entities": [(22, 28, "PERSON")]}),
    ("they say I'm akshay", {"entities": [(13, 19, "PERSON")]}),
    ("this is sudha", {"entities": [(8, 13, "PERSON")]}),
    ("I prefer to be called malathi", {"entities": [(22, 29, "PERSON")]}),
    ("say hi to bharath", {"entities": [(10, 17, "PERSON")]}),
    ("it's me, sandeep", {"entities": [(9, 16, "PERSON")]}),
    ("everyone calls me karthik", {"entities": [(18, 25, "PERSON")]}),
]
